Better anonymisation
rheinwerk-verlag/postgresql-anonymizer pull request #27
Opened 2021-07-02 04:31 UTC by nurikk

Hi, this PR improves data processing. Instead of doing `SELECT * FROM [source table]`, it does `SELECT col1, col2 FROM [source table]`. This reduces overall memory and network overhead on large table

2021-07-05 11:07 UTC, hkage requested changes

2021-07-05 11:09 UTC, hkage commented
This PR works perfectly with my database and I didn't get an Out of Memory error. No problem that you put both changes into one bigger pull request!

Thanks again for your work and time you put into this project right now!

2021-07-05 11:13 UTC, nurikk commented on pganonymizer/utils.py
> +    for i in trange(batches, desc="Processing {} batches for {}".format(batches, table), disable=not verbose):
This happens due to small batch size, try to increase it to something like 100-500k

2021-07-06 07:00 UTC, hkage approved these changes

2021-07-06 07:01 UTC, merged